{% set name = "weasyprint" %}
{% set version = "62.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a08ac400e11919d996d76becaa33160d7c1ac55ba160628c42ce7586574c1a51

build:
  skip: True    # [py<39]
  number: 0
  entry_points:
    - weasyprint = weasyprint.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python
    - flit-core >=3.2,<4
  run:
    - python
    - pydyf >=0.10.0
    - cffi >=0.6
    - html5lib >=1.1
    - tinycss2 >=1.3.0
    - cssselect2 >=0.1
    - Pyphen >=0.9.1
    - Pillow >=9.1.0
    # fonttools[woof]
    - fonttools >=4.0.0
    - zopfli >=0.1.4
    - brotli >=1.0.1
    # weasyprint attempts to load gobject & pango
    - glib
    - pango

{% set tests_to_ignore = [
  'test_acid2',
  'test_python_render',
  'test_unicode_filenames',
  'test_low_level_api',
  'test_url_fetcher',
  'test_page_copy_relative',
  'test_z_index',
  'test_unicode',
  'test_font_stretch',
  'test_table_vertical_align',
] %}
test:
  source_files:
    - tests
    - weasyprint/css/tests_ua.css
  imports:
    - weasyprint
  commands:
    - pip check
    - weasyprint --help
    - pytest -vv --ignore=tests/draw -k "not ({{ tests_to_ignore|join(' or ') }})"
  requires:
    - pip
    - pytest

about:
  home: https://www.courtbouillon.org/weasyprint
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: WeasyPrint converts web documents (HTML with CSS, SVG, …) to PDF
  description: |
    WeasyPrint is a smart solution helping people to create PDF documents. 
    You can generate gorgeous statistical reports, invoices, tickets, and anything you want 
    as long as you have some webdesign skills!
  doc_url: https://doc.courtbouillon.org/weasyprint/
  dev_url: https://github.com/Kozea/WeasyPrint

extra:
  recipe-maintainers:
    - mrandrewandrade
    - liZe
