{% set name = "WeasyPrint" %}
{% set version = "52.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Kozea/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3889680cc10bd167e5b31e21159730e40ed7bc77239e2ca22d80dcbe77596c52

build:
  number: 0
  noarch: python
  entry_points:
    - weasyprint = weasyprint.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - cairocffi >=0.9.0
    - cairosvg >=2.4.0
    - cffi >=0.6
    - cssselect2 >=0.1
    - html5lib >=0.999999999
    - pillow >=4.0.0
    - pango
    - pyphen >=0.9.1
    - python >=3.6
    - setuptools >=39.2.0
    - tinycss2 >=1.0.0

test:
  imports:
    - weasyprint
  commands:
    - pip check
    - weasyprint --help
    - pytest weasyprint/tests
  requires:
    - pip
    - pytest
  source_files:
    - weasyprint/tests
    

about:
  home: https://github.com/Kozea/WeasyPrint
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: WeasyPrint converts web documents (HTML with CSS, SVG, …) to PDF

  description: |
    WeasyPrint is a smart solution helping web developers to create PDF
    documents. It turns simple HTML pages into gorgeous statistical
    reports, invoices, tickets…

  doc_url: https://weasyprint.readthedocs.io/en/stable/
  dev_url: https://github.com/Kozea/WeasyPrint

extra:
  recipe-maintainers:
    - mrandrewandrade
    - liZe
