travis:
  secure:
    BINSTAR_TOKEN: HJzu5lcI7+m8Q4AG1gBj8BCqBF1GFvNm/DsiH4l3YcZchDjDktqHrca+t9I+khbfGsJlCNkjzcyz/wxa7TV+3l8XORMvLY1bWXfS0ci+Nfxe9/VRM7BTxusmM31Dd06lzgkf7YRBRNCB/YdWg0pcQHwj2qy8SQT9TW5v2hLsPZNKRH4qUIB0TMf/4FYP3IzUIjC0R2d1nXMiQBlvtJmkjvD4PZ5QoBEfgyGGyOr1WYvNaNjjfDAfxy1jSl6jiTEgaD2NNhik1seukiAWl400oLlEjho2cJ8NJJ/aZLqHYcwkuwjuWovGDC07yupMz9xKojG+TaMNfX475xPa0a2E4lE6Jmniht+RqfYwScZoGCCZx+dYPA/VJzrZY6s3YY85+tsz8cyW9hWkqGbDLu3DSZZTrOWEK9Ik7aztHo4yvW87elSdrOJONnMh/9VDnH2GHK/asOtBMcRZx12JKqkyeJop4JA8CQafmScMMwQxcId0vrRjYiPXcT5GYR4On3+pZort0JIbx0IWJELpvu6wMdIbGTZ2kWHt0L9oYj2sGboNkgdqgZsrr+HAKYs1AFA963lJF2+XHs1Rypf+mNO9fjDx16LEu2MS8h5TzrLTofDyqEKc0rIEgaWa/ufTZkaCjc80LO4wyDjTo7RvDCk9KufT7n4x7STF/tgvtWn2n2g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
