travis:
  secure:
    BINSTAR_TOKEN: 2zCjzQ9qz3BXcVwDE3CET4ikt5qhymND1ojRBnPEDzGZHc4j9AMn9ja6zz7paRCktU5JQjdkYG80u8kjwwT3pqwPYuHZ0wM6zu3osz/jV36mMneuFLXOSAc83dK3qTt+ljvRqbWCmACZwspZWBkQg/4G5ipyR4FEkn3oP/fmSvRPmQ1wQBMg2lpwYm3Nu3G353U6OWnZJlgoJmzzBtc2p0VEK+ADHu/YZXbi/EIF4vBrpTt2Areq73TzCWY4fwxKVmSHFopGrzWMGWm38qQpYMZoHS+IWo9b9XDHJT1Mquq5zqXsGMmiEhE/2SQd+B+KSec78/MI7Zx7tA7zWgiIHmygT15iPI1fslQk5nd/u0VXJ3crd45zeFrovIdBfC7/kcfR7ZMzGIeOxCkt5Orv7lbHz4LPDQmoFo9EdC7d3QySMiDxMzfEsGJyj4ROGWOmPIL8kdxFGWBdWd4eM5j6dmkwTRfh6glImXGSjFRyUBwC1kKHOZ/X/htTPMJpTjHdVuBDYjK9Ft+1pSw26lVDEbxcvqznxJjcx7w83ZtAdM2KVSN1PMGZOyzIdWVE87vljDHdMY25yUFl0qpBC0Ye/uBAMZBw3LNAcHrtv6zKrol5OzjYhPbGHnOTtEFiUS95yVLtg/VYyVudh0RghpERYpm2eE5ciVN819WCZMRmQNc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
